//! Generates the preset file list from `data/providers/`.
//!
//! `include_str!` needs a literal path, so a hand-written list would put every
//! provider's name in Rust — the defect gate 30 exists to catch, and it would
//! make adding a provider a code change after all. Walking the directory keeps
//! the promise: drop a `.toml` in, done.

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=data/providers");

    let mut names: Vec<String> = std::fs::read_dir(Path::new("data/providers"))
        .expect("data/providers must exist")
        .filter_map(|e| {
            let path = e.ok()?.path();
            (path.extension()? == "toml").then(|| path.file_stem()?.to_str().map(str::to_owned))?
        })
        .collect();
    // Sorted so the generated file, and therefore the preset order, is the same
    // on every machine (gate 42).
    names.sort();

    let mut out = String::from(
        "// Generated by build.rs from data/providers/. Do not edit.\n\
         pub(crate) static PRESETS: &[(&str, &str)] = &[\n",
    );
    for name in &names {
        writeln!(
            out,
            "    ({name:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/data/providers/{name}.toml\"))),"
        )
        .expect("writing to a String cannot fail");
    }
    out.push_str("];\n");

    let dest =
        Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR is set by cargo")).join("presets.rs");
    std::fs::write(dest, out).expect("the generated preset list must be writable");
}
